import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _currentLocale = const Locale('fr');

  Locale get currentLocale => _currentLocale;

  LanguageProvider() {
    _loadLocale();
  }

  Future<void> setLocale(String languageCode) async {
    _currentLocale = Locale(languageCode);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    String? code = prefs.getString('language_code');
    if (code != null) {
      _currentLocale = Locale(code);
      notifyListeners();
    }
  }

  String getText(String key) {
    // This would normally be backed by a map or arb files
    // For now, providing a simple mockup of key translation
    final translations = {
      'en': {
        'platform': 'PLATFORM',
        'dashboard': 'Dashboard',
        'restoration': 'Restoration',
        'services': 'SERVICES',
        'complaints': 'Complaints',
        'requests': 'Requests',
        'network': 'NETWORK',
        'community': 'Community',
        'messages': 'Messages',
        'profile': 'Profile',
        'settings': 'Settings',
        'logout': 'Logout',
        'account': 'ACCOUNT',
        'notifications': 'Notifications',
        'preferences': 'PREFERENCES',
        'dark_mode': 'Dark Mode',
        'language': 'Language',
        'assistance': 'ASSISTANCE',
        'help_center': 'Help Center',
        'contact_us': 'Contact Us',
        'about': 'ABOUT',
        'app_version': 'App Version',
        'terms_of_use': 'Terms of Use',
        'logout_confirm_title': 'Logout',
        'logout_confirm_msg': 'Are you sure you want to logout?',
        'cancel': 'Cancel',
        'confirm': 'Logout',
        'management': 'MANAGEMENT',
        'users': 'Users',
        'matricule_label': 'MATRICULE DU BAC',
        'password_label': 'MOT DE PASSE',
        'login_button': 'Log In',
        'secure_gateway': 'SECURE AUTHENTICATION GATEWAY',
        'err_fill_fields': 'Please fill all fields',
        'err_login_failed': 'Login failed',
        'welcome': 'Welcome,',
        'announcements': 'Announcements',
        'view_all': 'View all',
        'no_announcements': 'No announcements at the moment',
        'quick_actions': 'Quick Actions',
        'documents': 'Documents',
        'menu_today': "Today's Menu",
        'lunch': 'Lunch',
        'general': 'General',
        'ago_2h': '2h ago',
        'mes_annonces': 'My Announcements',
        'personal_info': 'Personal Information',
        'my_resident_card': 'MY RESIDENT CARD',
        'republic_algeria_1': 'ALGERIAN REPUBLIC',
        'republic_algeria_2': 'DEMOCRATIC AND POPULAR',
        'resident_card_title': 'RESIDENT CARD',
        'name_surname_label': 'NAME & SURNAME / الإسم و اللقب',
        'bloc_label': 'BLOC',
        'room_no_label': 'ROOM N°',
        'dob_label': 'DATE OF BIRTH',
        'scan_id': 'SCAN ID',
        'year_label': 'YEAR: 2023/2024',
        'valide': 'VALID',
        'no_name': 'No Name Found',
        'not_assigned': 'Not assigned',
      },
      'fr': {
        'platform': 'PLATEFORME',
        'dashboard': 'Dashboard',
        'restoration': 'Restauration',
        'services': 'SERVICES',
        'complaints': 'Réclamations',
        'requests': 'Demandes',
        'network': 'RÉSEAU',
        'community': 'Communauté',
        'messages': 'Messages',
        'profile': 'Profil',
        'settings': 'Paramètres',
        'logout': 'Déconnexion',
        'account': 'COMPTE',
        'notifications': 'Notifications',
        'preferences': 'PRÉFÉRENCES',
        'dark_mode': 'Mode Sombre',
        'language': 'Langue',
        'assistance': 'ASSISTANCE',
        'help_center': 'Centre d\'aide',
        'contact_us': 'Contactez-nous',
        'about': 'À PROPOS',
        'app_version': 'Version de l\'application',
        'terms_of_use': 'Conditions d\'utilisation',
        'logout_confirm_title': 'Déconnexion',
        'logout_confirm_msg': 'Êtes-vous sûr de vouloir vous déconnecter ?',
        'cancel': 'Annuler',
        'confirm': 'Déconnecter',
        'management': 'GESTION',
        'users': 'Utilisateurs',
        'matricule_label': 'MATRICULE DU BAC',
        'password_label': 'MOT DE PASSE',
        'login_button': 'Se connecter',
        'secure_gateway': 'PORTAIL D\'AUTHENTIFICATION SÉCURISÉ',
        'err_fill_fields': 'Veuillez remplir tous les champs',
        'err_login_failed': 'Échec de la connexion',
        'welcome': 'Bienvenue,',
        'announcements': 'Annonces',
        'view_all': 'Voir tout',
        'no_announcements': 'Aucune annonce pour le moment',
        'quick_actions': 'Actions Rapides',
        'documents': 'Documents',
        'menu_today': "Menu d'aujourd'hui",
        'lunch': 'Déjeuner',
        'general': 'Général',
        'ago_2h': 'Il y a 2h',
        'mes_annonces': 'Mes Annonces',
        'personal_info': 'Informations Personnelles',
        'my_resident_card': 'MA CARTE DE RÉSIDENT',
        'republic_algeria_1': 'RÉPUBLIQUE ALGÉRIENNE',
        'republic_algeria_2': 'DÉMOCRATIQUE ET POPULAIRE',
        'resident_card_title': 'CARTE RÉSIDENT',
        'name_surname_label': 'NOM & PRÉNOM / الإسم و اللقب',
        'bloc_label': 'BLOC',
        'room_no_label': 'N° CHAMBRE',
        'dob_label': 'DATE DE NAISSANCE',
        'scan_id': 'SCAN ID',
        'year_label': 'ANNÉE: 2023/2024',
        'valide': 'VALIDE',
        'no_name': 'Aucun nom trouvé',
        'not_assigned': 'Non assigné',
      },
      'ar': {
        'platform': 'المنصة',
        'dashboard': 'لوحة التحكم',
        'restoration': 'الإطعام',
        'services': 'الخدمات',
        'complaints': 'الشكاوى',
        'requests': 'الطلبات',
        'network': 'الشبكة',
        'community': 'المجتمع',
        'messages': 'الرسائل',
        'profile': 'الملف الشخصي',
        'settings': 'الإعدادات',
        'logout': 'تسجيل الخروج',
        'account': 'الحساب',
        'notifications': 'التنبيهات',
        'preferences': 'التفضيلات',
        'dark_mode': 'الوضع الليلي',
        'language': 'اللغة',
        'assistance': 'المساعدة',
        'help_center': 'مركز المساعدة',
        'contact_us': 'اتصل بنا',
        'about': 'حول',
        'app_version': 'نسخة التطبيق',
        'terms_of_use': 'شروط الاستخدام',
        'logout_confirm_title': 'تسجيل الخروج',
        'logout_confirm_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
        'cancel': 'إلغاء',
        'confirm': 'خروج',
        'management': 'الإدارة',
        'users': 'المستخدمين',
        'matricule_label': 'رقم التسجيل (باك)',
        'password_label': 'كلمة المرور',
        'login_button': 'تسجيل الدخول',
        'secure_gateway': 'بوابة تسجيل الدخول المؤمنة',
        'err_fill_fields': 'يرجى ملء جميع الحقول',
        'err_login_failed': 'فشل تسجيل الدخول',
        'welcome': 'مرحباً،',
        'announcements': 'الإعلانات',
        'view_all': 'مشاهدة الكل',
        'no_announcements': 'لا توجد إعلانات حالياً',
        'quick_actions': 'إجراءات سريعة',
        'documents': 'الوثائق',
        'menu_today': 'قائمة اليوم',
        'lunch': 'الغداء',
        'general': 'عام',
        'ago_2h': 'منذ ساعتين',
        'mes_annonces': 'إعلاناتي',
        'personal_info': 'المعلومات الشخصية',
        'my_resident_card': 'بطاقة الإقامة الخاصة بي',
        'republic_algeria_1': 'الجمهورية الجزائرية',
        'republic_algeria_2': 'الديمقراطية الشعبية',
        'resident_card_title': 'بطاقة مقيم',
        'name_surname_label': 'الإسم و اللقب / NOM & PRÉNOM',
        'bloc_label': 'الجناح',
        'room_no_label': 'رقم الغرفة',
        'dob_label': 'تاريخ الميلاد',
        'scan_id': 'مسح الهوية',
        'year_label': 'السنة: 2023/2024',
        'valide': 'صالحة',
        'no_name': 'لا يوجد إسم',
        'not_assigned': 'غير معين',
      },
    };
    return translations[_currentLocale.languageCode]?[key] ?? key;
  }
}
