import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _currentLocale = const Locale('fr');

  Locale get currentLocale => _currentLocale;

  LanguageProvider() {
    _loadLocale();
  }

  Future<void> setLocale(String languageCode) async {
    _currentLocale = Locale(languageCode);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    String? code = prefs.getString('language_code');
    if (code != null) {
      _currentLocale = Locale(code);
      notifyListeners();
    }
  }

  String getText(String key) {
    final translations = {
      'en': _en,
      'fr': _fr,
      'ar': _ar,
    };
    return translations[_currentLocale.languageCode]?[key] ?? key;
  }

  // ─── ENGLISH ───
  static const _en = {
    // Sidebar / Navigation
    'platform': 'PLATFORM',
    'dashboard': 'Dashboard',
    'restoration': 'Restoration',
    'services': 'SERVICES',
    'complaints': 'Complaints',
    'requests': 'Requests',
    'network': 'NETWORK',
    'community': 'Community',
    'messages': 'Messages',
    'profile': 'Profile',
    'settings': 'Settings',
    'logout': 'Logout',
    'logout_subtitle': 'Safely exit your session',
    'management': 'MANAGEMENT',
    'users': 'Users',
    'admin_dashboard': 'Admin Dashboard',
    'worker_dashboard': 'Worker Dashboard',

    // Settings
    'account': 'ACCOUNT',
    'notifications': 'Notifications',
    'alert_preferences': 'Alert preferences',
    'security': 'Security',
    'password_auth': 'Password & Authentication',
    'preferences': 'PREFERENCES',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'assistance': 'ASSISTANCE',
    'help_center': 'Help Center',
    'contact_us': 'Contact Us',
    'about': 'ABOUT',
    'app_version': 'App Version',
    'terms_of_use': 'Terms of Use',

    // Home
    'welcome': 'Welcome,',
    'announcements': 'Announcements',
    'recent_announcements': 'Recent Announcements',
    'view_all': 'View all',
    'no_announcements': 'No announcements at the moment',
    'quick_actions': 'Quick Actions',
    'quick_actions_title': 'Quick Actions',
    'report_problem': 'Report a problem',
    'menu_of_the_day': 'Menu of the day',
    'technical_services': 'Technical services',
    'docs_and_certs': 'Certs & Documents',
    'today_menu_available': "On Today's Menu",
    'lunch_available': 'LUNCH AVAILABLE',
    'documents': 'Documents',
    'menu_today': "Today's Menu",
    'lunch': 'Lunch',
    'general': 'General',
    'actualite': 'NEWS',
    'ago_2h': '2h ago',
    'mes_annonces': 'My Announcements',

    // Login
    'matricule_label': 'BAC MATRICULE',
    'password_label': 'PASSWORD',
    'login_button': 'Log In',
    'secure_gateway': 'SECURE AUTHENTICATION GATEWAY',
    'err_field_required': 'This field is required',
    'err_fill_fields': 'Please fill all fields',
    'err_login_failed': 'Login failed',
    'login_matricule': 'Matricule',
    'login_email': 'Email',
    'register': 'Register',
    'email_label': 'EMAIL',
    'full_name_label': 'FULL NAME',
    'role_label': 'ROLE',
    'student': 'Student',
    'worker': 'Worker',
    'administrator': 'Administrator',
    'department_label': 'DEPARTMENT',
    'residence_label': 'RESIDENCE',
    'confirm_password_label': 'CONFIRM PASSWORD',
    'already_have_account': 'Already have an account?',
    'no_account': 'Don\'t have an account?',
    'register_button': 'Create Account',
    'err_passwords_mismatch': 'Passwords do not match',
    'err_register_failed': 'Registration failed',
    'smart_residence': 'University Residence Platform',
    'forgot_password': 'Forgot password?',
    'biometric_login': 'Biometric Login',

    // Management & Statuses
    'status_received': 'Received',
    'status_in_progress': 'In Progress',
    'status_resolved': 'Resolved',
    'status_approved': 'Approved',
    'status_rejected': 'Rejected',
    'complaints_management': 'Complaints Management',
    'assign': 'Assign',
    'resolve': 'Resolve',
    'messaging': 'Support Chat',
    'write_message': 'Write a message...',
    'urgent_status': 'Urgent',
    'new_status': 'New',
    'worker_space': 'Worker Space',
    'my_assigned_tasks': 'My Assigned Tasks',
    'to_do': 'To Do',
    'done_tasks': 'Done',

    // Profile
    'my_profile': 'My Profile',
    'personal_info': 'Personal Information',
    'personal_info_subtitle': 'Manage your data',
    'logout_confirm_title': 'Logout',
    'logout_confirm_msg': 'Are you sure you want to logout your account?',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'logout_action': 'Logout',
    'my_resident_card': 'MY RESIDENT CARD',
    'republic_algeria_1': 'ALGERIAN REPUBLIC',
    'republic_algeria_2': 'DEMOCRATIC AND POPULAR',
    'resident_card_title': 'RESIDENT CARD',
    'student_card_title': 'STUDENT CARD',
    'name_surname_label': 'NAME & SURNAME',
    'name_surname_label_ar': 'الإسم و اللقب',
    'bloc_label': 'BLOC',
    'room_no_label': 'ROOM N°',
    'dob_label': 'DATE OF BIRTH',
    'scan_id': 'SCAN ID',
    'year_label': 'Academic Year: 2024/2025',
    'valide': 'VALID',
    'no_name': 'No Name Found',
    'not_assigned': 'Not assigned',
    'residence_card_ar': 'بطاقة الإقامة',
    'student_card_ar': 'بطاقة الطالب',
    'press_to_flip': 'Press to flip ↺',
    'ministry_he': 'Ministry of Higher Education and Scientific Research',
    'dou_bejaia': 'University Services Directorate Bejaia El Kseur',
    'esi_sba': 'Higher School of Computer Science Sidi Bel Abbes',
    'field': 'Field:',
    'it': 'Computer Science',
    'specialty': 'Specialty:',
    'is': 'Information Systems',

    // Complaints
    'my_complaints': 'My Complaints',
    'all_in_order': 'All in order!',
    'no_complaints_msg': 'You have no ongoing complaints.',
    'new_complaint': 'New Complaint',
    'complaint_title_label': 'Complaint title',
    'complaint_title_hint': 'e.g. Heating problem',
    'detailed_description': 'Detailed description',
    'describe_problem_hint': 'Describe your problem here...',
    'photo_optional': 'Photo (Optional)',
    'submit_complaint': 'SUBMIT COMPLAINT',
    'add_visual_proof': 'Add visual proof',
    'accepted_formats': 'Accepted formats: JPG, PNG',
    'details': 'Details',

    // Requests
    'my_requests': 'Requests',
    'repair': 'Repair',
    'repair_subtitle': 'Plumbing, Electricity, Carpentry',
    'cleaning': 'Cleaning',
    'cleaning_subtitle': 'Room, Hallway, Block',
    'housing': 'Housing',
    'housing_subtitle': 'Room change, Keys',
    'new_request': 'New Request',

    // Dining
    'dining_service': 'Dining',
    'service_of': 'Service of',
    'restaurant_open': 'Restaurant Open',
    'today': 'Today',
    'breakfast': 'Breakfast',
    'dinner': 'Dinner',
    'in_progress': 'IN PROGRESS',
    'menu_composition': 'MENU COMPOSITION',
    'rate_meal': 'Rate the meal',
    'breakfast_menu': 'Coffee, Milk, Bread, Jam, Butter',
    'lunch_menu': 'Couscous with vegetables, Meat, Mixed salad, Seasonal fruit',
    'dinner_menu': 'Lentil soup, Pasta with cheese, Yogurt',

    // Documents
    'housing_certificate': 'Housing certificate',
    'internal_rules': 'Internal rules',
    'departure_form': 'Departure form',

    // Forum
    'poll': 'Poll',
    'direction': 'Administration',

    // Admin Dashboard
    'admin_board': 'Dashboard',
    'hello_admin': 'Hello, Administrator',
    'manage_residence': 'Manage your residence in one place.',
    'total_students': 'Total Students',
    'complaints_handled': 'Complaints Handled',
    'free_rooms': 'Free Rooms',
    'vs_last_month': 'vs last month',
    'task_progress': 'Task Progress',
    'tasks_completed': 'Tasks Completed',
    'completed': 'Completed',
    'in_progress_legend': 'In progress',
    'pending': 'Pending',
    'quick_management': 'Quick Management',
    'manage_students': 'Manage Students',
    'registered_users': 'registered users',
    'manage_complaints': 'Manage Complaints',
    'pending_complaints': 'pending complaints',
    'meal_config': 'Meal Configuration',
    'modify_weekly_menu': 'Modify weekly menu',
    'global_announcements': 'Global Announcements',
    'broadcast_message': 'Broadcast an important message',
    'add_task': 'Add a Task',
    'admin_settings': 'Settings',
    'dark_mode_admin': 'Dark Mode',
    'language_admin': 'Language',
    'disconnect': 'Disconnect',

    // Admin Specific
    'priority_urgent': 'URGENT',
    'priority_medium': 'MEDIUM',
    'priority_normal': 'NORMAL',
    'students_management': 'Students Management',
    'search_student': 'Search a student...',
    'total': 'Total',
    'active': 'Active',
    'blocked': 'Blocked',
    'edit': 'Edit',
    'block': 'Block',
    'unblock': 'Unblock',
    'announcements_comm': 'Announcements & Communication',
    'create_announcement': 'Create a new announcement',
    'communicate_residents': 'Communicate with all residents instantly.',
    'message_history': 'Message history',
    'broadcast': 'Broadcast',
    'urgent': 'URGENT',
    'info': 'INFO',

    // New Forum Keys
    'create_post': 'Create Post',
    'post_text_hint': 'What\'s on your mind?',
    'add_image': 'Add Image',
    'create_poll': 'Create Poll',
    'poll_question': 'Poll Question',
    'add_option': 'Add Option',
    'post_button': 'Post',
    'liked': 'Liked',
    'replies': 'Replies',
    'write_reply': 'Write a reply...',
    'no_posts': 'No posts yet. Be the first to share something!',
    'official_announcement': 'OFFICIAL',
    
    // Sports & Showers
    'sports_and_showers': 'Sports & Showers',
    'sports_subtitle': 'Program and showers',
    'sports_program': 'Sports Hall Program',
    'mens_showers': 'Men\'s Showers',
    'womens_showers': 'Women\'s Showers',
    'schedule_tba': 'Schedule to be announced',
    'team_registration': 'Team Registration',
    'football': 'Football',
    'volleyball': 'Volleyball',
    'basketball': 'Basketball',
    'join_team': 'Join Team',
    'registration_sent_msg': 'Registration request sent successfully!',
    'feature_coming_soon': 'Feature coming soon!',
  };

  // ─── FRENCH ───
  static const _fr = {
    // Sidebar / Navigation
    'platform': 'PLATEFORME',
    'dashboard': 'Dashboard',
    'restoration': 'Restauration',
    'services': 'SERVICES',
    'complaints': 'Réclamations',
    'requests': 'Demandes',
    'network': 'RÉSEAU',
    'community': 'Communauté',
    'messages': 'Messages',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'logout': 'Déconnexion',
    'logout_subtitle': 'Quitter la session en toute sécurité',
    'management': 'GESTION',
    'users': 'Utilisateurs',
    'admin_dashboard': 'Admin Dashboard',
    'worker_dashboard': 'Espace Travailleur',

    // Settings
    'account': 'COMPTE',
    'notifications': 'Notifications',
    'alert_preferences': 'Préférences d\'alerte',
    'security': 'Sécurité',
    'password_auth': 'Mot de passe & Authentification',
    'preferences': 'PRÉFÉRENCES',
    'dark_mode': 'Mode Sombre',
    'language': 'Langue',
    'assistance': 'ASSISTANCE',
    'help_center': 'Centre d\'aide',
    'contact_us': 'Contactez-nous',
    'about': 'À PROPOS',
    'app_version': 'Version de l\'application',
    'terms_of_use': 'Conditions d\'utilisation',

    // Home
    'welcome': 'Bienvenue,',
    'announcements': 'Annonces',
    'recent_announcements': 'Annonces Récentes',
    'view_all': 'Voir tout',
    'no_announcements': 'Aucune annonce pour le moment',
    'quick_actions': 'Actions Rapides',
    'quick_actions_title': 'Actions Rapides',
    'report_problem': 'Signaler un problème',
    'menu_of_the_day': 'Menu du jour',
    'technical_services': 'Services techniques',
    'docs_and_certs': 'Attestations & Certifs',
    'today_menu_available': "Au Menu Aujourd'hui",
    'lunch_available': 'DÉJEUNER DISPONIBLE',
    'documents': 'Documents',
    'menu_today': "Menu d'aujourd'hui",
    'lunch': 'Déjeuner',
    'general': 'Général',
    'actualite': 'ACTUALITÉ',
    'ago_2h': 'Il y a 2h',
    'mes_annonces': 'Mes Annonces',

    // Login
    'matricule_label': 'MATRICULE DU BAC',
    'password_label': 'MOT DE PASSE',
    'login_button': 'Se connecter',
    'secure_gateway': 'PORTAIL D\'AUTHENTIFICATION SÉCURISÉ',
    'err_field_required': 'Ce champ est obligatoire',
    'err_fill_fields': 'Veuillez remplir tous les champs',
    'err_login_failed': 'Échec de la connexion',
    'login_matricule': 'Matricule',
    'login_email': 'Email',
    'register': 'S\'inscrire',
    'email_label': 'E-MAIL',
    'full_name_label': 'NOM COMPLET',
    'role_label': 'RÔLE',
    'student': 'Étudiant',
    'worker': 'Travailleur',
    'administrator': 'Administrateur',
    'department_label': 'DÉPARTEMENT',
    'residence_label': 'RÉSIDENCE',
    'confirm_password_label': 'CONFIRMER LE MOT DE PASSE',
    'already_have_account': 'Déjà un compte ?',
    'no_account': 'Pas de compte ?',
    'register_button': 'Créer un compte',
    'err_passwords_mismatch': 'Les mots de passe ne correspondent pas',
    'err_register_failed': 'Échec de l\'inscription',
    'smart_residence': 'Plateforme de Résidence Universitaire',
    'forgot_password': 'Mot de passe oublié ?',
    'biometric_login': 'Connexion biométrique',

    // Profile
    'my_profile': 'Mon Profil',
    'personal_info': 'Informations Personnelles',
    'personal_info_subtitle': 'Gérer vos données',
    'logout_confirm_title': 'Déconnexion',
    'logout_confirm_msg': 'Voulez-vous vraiment vous déconnecter de votre compte ?',
    'cancel': 'Annuler',
    'confirm': 'Confirmer',
    'logout_action': 'Déconnecter',
    'my_resident_card': 'MA CARTE DE RÉSIDENT',
    'republic_algeria_1': 'RÉPUBLIQUE ALGÉRIENNE',
    'republic_algeria_2': 'DÉMOCRATIQUE ET POPULAIRE',
    'resident_card_title': 'CARTE RÉSIDENT',
    'student_card_title': 'CARTE ÉTUDIANT',
    'name_surname_label': 'NOM & PRÉNOM',
    'name_surname_label_ar': 'الإسم و اللقب',
    'bloc_label': 'BLOC',
    'room_no_label': 'N° CHAMBRE',
    'dob_label': 'DATE DE NAISSANCE',
    'scan_id': 'SCAN ID',
    'year_label': 'Année Universitaire: 2024/2025',
    'valide': 'VALIDE',
    'no_name': 'Aucun nom trouvé',
    'not_assigned': 'Non assigné',
    'residence_card_ar': 'بطاقة الإقامة',
    'student_card_ar': 'بطاقة الطالب',
    'press_to_flip': 'Appuyez pour retourner ↺',
    'ministry_he': 'Ministère de l\'Enseignement Supérieur et de la Recherche Scientifique',
    'dou_bejaia': 'Direction des Œuvres Universitaires Béjaïa El Kseur',
    'esi_sba': 'École Supérieure en Informatique Sidi Bel Abbès',
    'field': 'Domaine:',
    'it': 'Informatique',
    'specialty': 'Spécialité:',
    'is': 'Systèmes d\'Information',

    // Complaints
    'my_complaints': 'Mes Réclamations',
    'all_in_order': 'Tout est en ordre !',
    'no_complaints_msg': 'Vous n\'avez aucune réclamation en cours.',
    'new_complaint': 'Nouvelle Réclamation',
    'complaint_title_label': 'Titre de la réclamation',
    'complaint_title_hint': 'ex: Problème de chauffage',
    'detailed_description': 'Description détaillée',
    'describe_problem_hint': 'Expliquez votre problème ici...',
    'photo_optional': 'Photo (Optionnel)',
    'submit_complaint': 'ENVOYER LA RÉCLAMATION',
    'add_visual_proof': 'Ajouter une preuve visuelle',
    'accepted_formats': 'Formats acceptés: JPG, PNG',
    'details': 'Détails',
    'status_received': 'Reçu',
    'status_in_progress': 'En cours',
    'status_resolved': 'Résolu',
    'status_approved': 'Approuvé',
    'status_rejected': 'Rejeté',

    // Requests
    'my_requests': 'Demandes',
    'repair': 'Réparation',
    'repair_subtitle': 'Plomberie, Électricité, Menuiserie',
    'cleaning': 'Nettoyage',
    'cleaning_subtitle': 'Chambre, Couloir, Bloc',
    'housing': 'Hébergement',
    'housing_subtitle': 'Changement de chambre, Clés',
    'new_request': 'Nouvelle Demande',

    // Dining
    'dining_service': 'Restauration',
    'service_of': 'Service de',
    'restaurant_open': 'Restaurant Ouvert',
    'today': "Aujourd'hui",
    'breakfast': 'Petit-déjeuner',
    'dinner': 'Dîner',
    'in_progress': 'EN COURS',
    'menu_composition': 'COMPOSITION DU MENU',
    'rate_meal': 'Noter le repas',
    'breakfast_menu': 'Café, Lait, Pain, Confiture, Beurre',
    'lunch_menu': 'Couscous aux légumes, Viande, Salade variée, Fruit de saison',
    'dinner_menu': 'Soupe de lentilles, Pâtes au fromage, Yaourt',

    // Chat
    'messaging': 'Messagerie',
    'write_message': 'Écrire un message...',

    // Documents
    'housing_certificate': 'Certificat d\'hébergement',
    'internal_rules': 'Règlement intérieur',
    'departure_form': 'Formulaire de départ',

    // Forum
    'poll': 'Sondage',
    'direction': 'Direction',

    // Admin Dashboard
    'admin_board': 'Tableau de Bord',
    'hello_admin': 'Bonjour, Administrateur',
    'manage_residence': 'Gérez votre résidence en un seul endroit.',
    'total_students': 'Total Étudiants',
    'complaints_handled': 'Plaintes Traitées',
    'free_rooms': 'Chambres Libres',
    'vs_last_month': 'vs mois dernier',
    'task_progress': 'Progression des Tâches',
    'tasks_completed': 'Tâches Complétées',
    'completed': 'Complété',
    'in_progress_legend': 'En cours',
    'pending': 'En attente',
    'quick_management': 'Gestion Rapide',
    'manage_students': 'Gérer les Étudiants',
    'registered_users': 'utilisateurs enregistrés',
    'manage_complaints': 'Gérer les Réclamations',
    'pending_complaints': 'plaintes en attente',
    'meal_config': 'Configuration Repas',
    'modify_weekly_menu': 'Modifier le menu hebdomadaire',
    'global_announcements': 'Annonces Globales',
    'broadcast_message': 'Diffuser un message important',
    'add_task': 'Ajouter une Tâche',
    'admin_settings': 'Paramètres',
    'dark_mode_admin': 'Mode Sombre',
    'language_admin': 'Langue',
    'disconnect': 'Déconnexion',

    // Admin Complaints
    'complaints_management': 'Gestion des Réclamations',
    'assign': 'Assigner',
    'resolve': 'Résoudre',
    'priority_urgent': 'URGENT',
    'priority_medium': 'MOYEN',
    'priority_normal': 'NORMAL',

    // Admin Users
    'students_management': 'Gestion des Étudiants',
    'search_student': 'Rechercher un étudiant...',
    'total': 'Total',
    'active': 'Actifs',
    'blocked': 'Bloqués',
    'edit': 'Modifier',
    'block': 'Bloquer',
    'unblock': 'Débloquer',

    // Admin Announcements
    'announcements_comm': 'Annonces & Communication',
    'create_announcement': 'Créer une nouvelle annonce',
    'communicate_residents': 'Communiquez avec tous les résidents instantanément.',
    'message_history': 'Historique des messages',
    'broadcast': 'Diffuser',
    'urgent': 'URGENT',
    'info': 'INFO',

    // New Forum Keys
    'create_post': 'Créer un post',
    'post_text_hint': 'À quoi pensez-vous ?',
    'add_image': 'Ajouter une image',
    'create_poll': 'Créer un sondage',
    'poll_question': 'Question du sondage',
    'add_option': 'Ajouter une option',
    'post_button': 'Publier',
    'liked': 'Aimé',
    'replies': 'Réponses',
    'write_reply': 'Écrire une réponse...',
    'no_posts': 'Aucun post pour le moment. Soyez le premier à partager !',
    'official_announcement': 'OFFICIEL',

    // Sports & Showers
    'sports_and_showers': 'Sports & Douches',
    'sports_subtitle': 'Programme et douches',
    'sports_program': 'Programme de la Salle de Sport',
    'mens_showers': 'Douches Hommes',
    'womens_showers': 'Douches Filles',
    'schedule_tba': 'Horaires à venir',
    'team_registration': 'Inscription aux équipes',
    'football': 'Football',
    'volleyball': 'Volleyball',
    'basketball': 'Basketball',
    'join_team': 'S\'inscrire',
    'registration_sent_msg': 'Demande d\'inscription envoyée avec succès !',

    // Worker Dashboard
    'worker_space': 'Espace Travailleur',
    'my_assigned_tasks': 'Mes Tâches Assignées',
    'to_do': 'À faire',
    'done_tasks': 'Terminés',
    'urgent_status': 'Urgent',
    'new_status': 'Nouveau',
    'feature_coming_soon': 'Bientôt disponible !',
  };

  // ─── ARABIC ───
  static const _ar = {
    // Sidebar / Navigation
    'platform': 'المنصة',
    'dashboard': 'لوحة التحكم',
    'restoration': 'الإطعام',
    'services': 'الخدمات',
    'complaints': 'الشكاوى',
    'requests': 'الطلبات',
    'network': 'الشبكة',
    'community': 'المجتمع',
    'messages': 'الرسائل',
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'logout': 'تسجيل الخروج',
    'logout_subtitle': 'الخروج من الجلسة بأمان',
    'management': 'الإدارة',
    'users': 'المستخدمين',
    'admin_dashboard': 'لوحة التحكم',
    'worker_dashboard': 'فضاء العامل',

    // Settings
    'account': 'الحساب',
    'notifications': 'التنبيهات',
    'alert_preferences': 'تفضيلات التنبيه',
    'security': 'الأمان',
    'password_auth': 'كلمة المرور والمصادقة',
    'preferences': 'التفضيلات',
    'dark_mode': 'الوضع الليلي',
    'language': 'اللغة',
    'assistance': 'المساعدة',
    'help_center': 'مركز المساعدة',
    'contact_us': 'اتصل بنا',
    'about': 'حول',
    'app_version': 'نسخة التطبيق',
    'terms_of_use': 'شروط الاستخدام',

    // Home
    'welcome': 'مرحباً،',
    'announcements': 'الإعلانات',
    'recent_announcements': 'الإعلانات الأخيرة',
    'view_all': 'مشاهدة الكل',
    'no_announcements': 'لا توجد إعلانات حالياً',
    'quick_actions': 'إجراءات سريعة',
    'quick_actions_title': 'إجراءات سريعة',
    'report_problem': 'الإبلاغ عن مشكلة',
    'menu_of_the_day': 'قائمة الطعام',
    'technical_services': 'الخدمات التقنية',
    'docs_and_certs': 'الشهادات والوثائق',
    'today_menu_available': 'قائمة اليوم متوفرة',
    'lunch_available': 'الغداء متوفر',
    'documents': 'الوثائق',
    'menu_today': 'قائمة اليوم',
    'lunch': 'الغداء',
    'general': 'عام',
    'actualite': 'آخر الأخبار',
    'ago_2h': 'منذ ساعتين',
    'mes_annonces': 'إعلاناتي',

    // Login
    'matricule_label': 'رقم التسجيل',
    'password_label': 'كلمة المرور',
    'login_button': 'دخول',
    'secure_gateway': 'بوابة تسجيل دخول آمنة',
    'err_field_required': 'هذا الحقل مطلوب',
    'err_fill_fields': 'يرجى ملء جميع الحقول',
    'err_login_failed': 'فشل تسجيل الدخول',
    'login_matricule': 'رقم التسجيل',
    'login_email': 'البريد الإلكتروني',
    'register': 'تسجيل',
    'email_label': 'البريد الإلكتروني',
    'full_name_label': 'الاسم الكامل',
    'role_label': 'الدور',
    'student': 'طالب',
    'worker': 'عامل',
    'administrator': 'مشرف',
    'department_label': 'القسم',
    'residence_label': 'الإقامة',
    'confirm_password_label': 'تأكيد كلمة المرور',
    'already_have_account': 'لديك حساب بالفعل؟',
    'no_account': 'ليس لديك حساب؟',
    'register_button': 'إنشاء حساب',
    'err_passwords_mismatch': 'كلمات المرور غير متطابقة',
    'err_register_failed': 'فشل التسجيل',
    'smart_residence': 'منصة الإقامة الجامعية',
    'forgot_password': 'نسيت كلمة المرور؟',
    'biometric_login': 'تسجيل بصمة',

    // Profile
    'my_profile': 'ملفي الشخصي',
    'personal_info': 'المعلومات الشخصية',
    'personal_info_subtitle': 'إدارة بياناتك',
    'logout_confirm_title': 'تسجيل الخروج',
    'logout_confirm_msg': 'هل أنت متأكد من رغبتك في تسجيل الخروج من حسابك؟',
    'cancel': 'إلغاء',
    'confirm': 'تأكيد',
    'logout_action': 'خروج',
    'my_resident_card': 'بطاقة الإقامة',
    'republic_algeria_1': 'الجمهورية الجزائرية',
    'republic_algeria_2': 'الديمقراطية الشعبية',
    'resident_card_title': 'بطاقة مقيم',
    'student_card_title': 'بطاقة طالب',
    'name_surname_label': 'الإسم و اللقب',
    'name_surname_label_ar': 'الإسم و اللقب',
    'bloc_label': 'الجناح',
    'room_no_label': 'رقم الغرفة',
    'dob_label': 'تاريخ الميلاد',
    'scan_id': 'مسح الكود',
    'year_label': 'السنة الجامعية: 2024/2025',
    'valide': 'صالحة',
    'no_name': 'لا يوجد إسم',
    'not_assigned': 'غير معين',
    'residence_card_ar': 'بطاقة الإقامة',
    'student_card_ar': 'بطاقة الطالب',
    'press_to_flip': 'إضغط للقلب ↺',
    'ministry_he': 'وزارة التعليم العالي والبحث العلمي',
    'dou_bejaia': 'مديرية الخدمات الجامعية بجاية القصر',
    'esi_sba': 'المدرسة العليا للإعلام الآلي سيدي بلعباس',
    'field': 'الميدان:',
    'it': 'إعلام آلي',
    'specialty': 'التخصص:',
    'is': 'نظم المعلومات',

    // Complaints
    'my_complaints': 'شكاواي',
    'all_in_order': 'كل شيء على ما يرام!',
    'no_complaints_msg': 'ليس لديك أي شكاوى جارية.',
    'new_complaint': 'شكوى جديدة',
    'complaint_title_label': 'عنوان الشكوى',
    'complaint_title_hint': 'مثال: مشكلة التدفئة',
    'detailed_description': 'وصف مفصل',
    'describe_problem_hint': 'اشرح مشكلتك هنا...',
    'photo_optional': 'صورة (اختياري)',
    'submit_complaint': 'إرسال الشكوى',
    'add_visual_proof': 'إضافة دليل مرئي',
    'accepted_formats': 'الصيغ المقبولة: JPG, PNG',
    'details': 'التفاصيل',
    'status_received': 'مستلمة',
    'status_in_progress': 'قيد المعالجة',
    'status_resolved': 'تم الحل',
    'status_approved': 'مقبولة',
    'status_rejected': 'مرفوضة',
    'complaints_management': 'إدارة الشكاوى',
    'assign': 'تعيين',
    'resolve': 'حل',
    'messaging': 'دردشة الدعم',
    'write_message': 'اكتب رسالة...',
    'urgent_status': 'عاجل',
    'new_status': 'جديد',
    'worker_space': 'فضاء العامل',
    'my_assigned_tasks': 'مهامي المعينة',
    'to_do': 'للقيام به',
    'done_tasks': 'مكتملة',

    // Requests
    'my_requests': 'الطلبات',
    'repair': 'إصلاح',
    'repair_subtitle': 'سباكة، كهرباء، نجارة',
    'cleaning': 'تنظيف',
    'cleaning_subtitle': 'غرفة، ممر، جناح',
    'housing': 'إيواء',
    'housing_subtitle': 'تغيير غرفة، مفاتيح',
    'new_request': 'طلب جديد',

    // Dining
    'dining_service': 'الإطعام',
    'service_of': 'خدمة',
    'restaurant_open': 'المطعم مفتوح',
    'today': 'اليوم',
    'breakfast': 'الفطور',
    'dinner': 'العشاء',
    'in_progress': 'جاري',
    'menu_composition': 'تركيبة الوجبة',
    'rate_meal': 'تقييم الوجبة',
    'breakfast_menu': 'قهوة، حليب، خبز، مربى، زبدة',
    'lunch_menu': 'كسكس بالخضر، لحم، سلطة منوعة، فاكهة الموسم',
    'dinner_menu': 'شوربة عدس، معكرونة بالجبن، ياغورت',

    // Documents
    'housing_certificate': 'شهادة الإقامة',
    'internal_rules': 'النظام الداخلي',
    'departure_form': 'استمارة المغادرة',

    // Forum
    'poll': 'استطلاع',
    'direction': 'الإدارة',

    // Admin Dashboard
    'admin_board': 'لوحة التحكم',
    'hello_admin': 'مرحباً، المدير',
    'manage_residence': 'أدر إقامتك في مكان واحد.',
    'total_students': 'إجمالي الطلبة',
    'complaints_handled': 'الشكاوى المعالجة',
    'free_rooms': 'الغرف الشاغرة',
    'vs_last_month': 'مقارنة بالشهر الماضي',
    'task_progress': 'تقدم المهام',
    'tasks_completed': 'المهام المنجزة',
    'completed': 'منجزة',
    'in_progress_legend': 'قيد التنفيذ',
    'pending': 'في الانتظار',
    'quick_management': 'إدارة سريعة',
    'manage_students': 'إدارة الطلبة',
    'registered_users': 'مستخدم مسجل',
    'manage_complaints': 'إدارة الشكاوى',
    'pending_complaints': 'شكوى في الانتظار',
    'meal_config': 'إعداد الوجبات',
    'modify_weekly_menu': 'تعديل القائمة الأسبوعية',
    'global_announcements': 'إعلانات عامة',
    'broadcast_message': 'بث رسالة مهمة',
    'add_task': 'إضافة مهمة',
    'admin_settings': 'الإعدادات',
    'dark_mode_admin': 'الوضع الليلي',
    'language_admin': 'اللغة',
    'disconnect': 'تسجيل الخروج',

    // Admin Specific
    'priority_urgent': 'عاجل',
    'priority_medium': 'متوسط',
    'priority_normal': 'عادي',
    'students_management': 'إدارة الطلبة',
    'search_student': 'البحث عن طالب...',
    'total': 'المجموع',
    'active': 'نشط',
    'blocked': 'محظور',
    'edit': 'تعديل',
    'block': 'حظر',
    'unblock': 'إلغاء الحظر',
    'announcements_comm': 'الإعلانات والتواصل',
    'create_announcement': 'إنشاء إعلان جديد',
    'communicate_residents': 'تواصل مع جميع المقيمين فوراً.',
    'message_history': 'سجل الرسائل',
    'official_announcement': 'رسمي',
    'create_post': 'إنشاء منشور',
    'post_text_hint': 'بماذا تفكر؟',
    'add_image': 'إضافة صورة',
    'create_poll': 'إنشاء استطلاع',
    'poll_question': 'سؤال الاستطلاع',
    'add_option': 'إضافة خيار',
    'post_button': 'نشر',
    'liked': 'أعجبني',
    'replies': 'الردود',
    'write_reply': 'اكتب رداً...',
    'no_posts': 'لا توجد منشورات بعد. كن أول من يشارك شيئاً!',

    // Sports & Showers
    'sports_and_showers': 'الرياضة والاستحمام',
    'sports_subtitle': 'البرنامج والاستحمام',
    'sports_program': 'برنامج القاعة الرياضية',
    'mens_showers': 'حمامات الذكور',
    'womens_showers': 'حمامات الإناث',
    'schedule_tba': 'سيتم إضافة الأوقات لاحقاً',
    'team_registration': 'التسجيل في الفرق الرياضية',
    'football': 'كرة القدم',
    'volleyball': 'الكرة الطائرة',
    'basketball': 'كرة السلة',
    'join_team': 'انضم للفريق',
    'registration_sent_msg': 'تم إرسال طلب التسجيل بنجاح!',
    'feature_coming_soon': 'الميزة قيد التطوير!',
  };
}
