// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGR1bvdhVrqCIuy2qSmHDxpRghovER3qk',
    appId: '1:229444084306:web:626cd5d1e3b32f0870b58b',
    messagingSenderId: '229444084306',
    projectId: 'iqamty-estin-pp',
    authDomain: 'iqamty-estin-pp.firebaseapp.com',
    storageBucket: 'iqamty-estin-pp.firebasestorage.app',
    measurementId: 'G-JVL08FMZTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCs0-59kMO7wMKZdApfhpqu_qeN-UNAAo',
    appId: '1:229444084306:android:6236f84693e8540170b58b',
    messagingSenderId: '229444084306',
    projectId: 'iqamty-estin-pp',
    storageBucket: 'iqamty-estin-pp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFJJ3iFjJNkefQSMOamRcZBT6qYcZ4FLM',
    appId: '1:229444084306:ios:daab73994a4bcd4370b58b',
    messagingSenderId: '229444084306',
    projectId: 'iqamty-estin-pp',
    storageBucket: 'iqamty-estin-pp.firebasestorage.app',
    iosBundleId: 'com.example.iqamty',
  );

}